site_name: RVBUST CSharp SDK

nav:
  - 首页: index.md
  - 配置步骤:
    - Steps/Prerequisite.md
    - Steps/CSharpExample.md
    - Steps/CSharpWindows.md
  - 图像获取流程:
    - Process/CSharpProcess.md
    - Process/CSharpParameter.md
  - 支持:
    - Support/FAQ.md
    - Support/Changelog.md

theme: 
  name: material
  language: zh
  logo: assets/images/RVLogo.png
  favicon: assets/images/RVLogo.png

plugins:
  - search:
      lang: 
          - en
          - ja
          - zh
      separator: '[\s\-\.]+'

# extra:
#  version:
#    provider: mike      

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
      